### ISSUE TITLE
`poetry install` fails with TypeError when run from `nox`

### ISSUE THREAD

**Issue by ToddG** [cjolowicz/hypermodern-python#18]
**REPRO**
* clone this repo
* check out the chapter07 branch
* run nox

**ERROR**
```bash
[TypeError]
expected string or bytes-like object
```

**LOG**
```bash
06:24 $ git log | head
commit 71dab2c92819ba95a25fa4e4127d9ea62a580c93
Author: Claudio Jolowicz <claudio.jolowicz@cyren.com>
Date:   Thu Nov 21 09:20:04 2019 +0100

    Add Docker Hub badge

commit d288141b13628db345453923a63cbaa32d801819
Author: Claudio Jolowicz <claudio.jolowicz@cyren.com>
Date:   Wed Nov 20 19:25:17 2019 +0100

✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
06:24 $ nox
nox > Running session lint-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/lint-3-8
nox > pip install flake8 flake8-annotations flake8-bandit flake8-black flake8-bugbear flake8-docstrings flake8-import-order darglint
nox > flake8 src tests noxfile.py docs/conf.py
nox > Session lint-3.8 was successful.
nox > Running session lint-3.7
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/lint-3-7
nox > pip install flake8 flake8-annotations flake8-bandit flake8-black flake8-bugbear flake8-docstrings flake8-import-order darglint
nox > flake8 src tests noxfile.py docs/conf.py
nox > Session lint-3.7 was successful.
nox > Running session mypy-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/mypy-3-8
nox > pip install mypy
nox > mypy src tests noxfile.py docs/conf.py
Success: no issues found in 9 source files
nox > Session mypy-3.8 was successful.
nox > Running session mypy-3.7
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/mypy-3-7
nox > pip install mypy
nox > mypy src tests noxfile.py docs/conf.py
Success: no issues found in 9 source files
nox > Session mypy-3.7 was successful.
nox > Running session pytype
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/pytype
nox > pip install pytype
nox > pytype --config=pytype.cfg src tests noxfile.py docs/conf.py
Computing dependencies
Analyzing 9 sources with 0 local dependencies
ninja: Entering directory `/Users/tdgreenw/repos/ext/hypermodern-python/.pytype'
[9/9] check tests.conftest
Success: no errors found
nox > Session pytype was successful.
nox > Running session tests-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/tests-3-8
nox > poetry install

[TypeError]
expected string or bytes-like object
nox > Command poetry install failed with exit code 1
nox > Session tests-3.8 failed.
nox > Running session tests-3.7
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/tests-3-7
nox > poetry install

[TypeError]
expected string or bytes-like object
nox > Command poetry install failed with exit code 1
nox > Session tests-3.7 failed.
nox > Ran multiple sessions:
nox > * lint-3.8: success
nox > * lint-3.7: success
nox > * mypy-3.8: success
nox > * mypy-3.7: success
nox > * pytype: success
nox > * tests-3.8: failed
nox > * tests-3.7: failed
```

**Comment by ToddG** [comment]
**Links**
* https://stackoverflow.com/questions/59768651/how-to-use-nox-with-poetry#new-answer
* https://python-poetry.org/docs/cli/
* https://nox.thea.codes/en/stable/config.html

**Comment by ToddG** [comment]
Adding a verbose flag to the `poetry install` line in the noxfile yields the following:

**Changes**
```bash
06:37 $ git diff
diff --git a/noxfile.py b/noxfile.py
index b505d38..c5668a9 100644
--- a/noxfile.py
+++ b/noxfile.py
@@ -52,7 +52,7 @@ def pytype(session: Session) -> None:
 def tests(session: Session) -> None:
     """Run the test suite."""
     args = session.posargs or ["--cov", "--xdoctest"]
-    session.run("poetry", "install", external=True)
+    session.run("poetry", "install", "-v", external=True)
     session.run("pytest", *args)


@@ -67,5 +67,5 @@ def coverage(session: Session) -> None:
 @nox.session(python="3.8")
 def docs(session: Session) -> None:
     """Build the documentation."""
-    session.run("poetry", "install", "--extras=docs", external=True)
+    session.run("poetry", "install", "-v", "--extras=docs", external=True)
     session.run("sphinx-build", "docs", "docs/_build")
```
**Output**
```bash
nox > poetry install -v
Using virtualenv: /Users/tdgreenw/repos/ext/hypermodern-python/.nox/tests-3-8

[TypeError]
expected string or bytes-like object

Traceback (most recent call last):
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/tdgreenw/.poetry/lib/poetry/console/commands/install.py", line 47, in handle
    installer = Installer(
  File "/Users/tdgreenw/.poetry/lib/poetry/installation/installer.py", line 55, in __init__
    installed = self._get_installed()
  File "/Users/tdgreenw/.poetry/lib/poetry/installation/installer.py", line 488, in _get_installed
    return InstalledRepository.load(self._env)
  File "/Users/tdgreenw/.poetry/lib/poetry/repositories/installed_repository.py", line 26, in load
    package = Package(name, version, version)
  File "/Users/tdgreenw/.poetry/lib/poetry/packages/package.py", line 42, in __init__
    self._name = canonicalize_name(name)
  File "/Users/tdgreenw/.poetry/lib/poetry/utils/helpers.py", line 26, in canonicalize_name
    return _canonicalize_regex.sub("-", name).lower()
```

**Comment by ToddG** [comment]
Added some prints to the helpers.py to see what's breaking in the canonicalize method...

**CHANGES**
```python
def canonicalize_name(name):  # type: (str) -> str
    print('canonicalize_name: %s' % name)
    cname =  _canonicalize_regex.sub("-", name).lower()
    print('cname: %s' % cname)
    return cname
```

**REPRO**
```bash
nox -r
```

**OUTPUT**
```bash
nox > Re-using existing virtual environment at .nox/tests-3-8.
nox > poetry install -v
canonicalize_name: hypermodern-python
cname: hypermodern-python
canonicalize_name: click
cname: click
canonicalize_name: sphinx
cname: sphinx
canonicalize_name: sphinx-rtd-theme
cname: sphinx-rtd-theme
canonicalize_name: sphinx-autodoc-typehints
cname: sphinx-autodoc-typehints
canonicalize_name: pytest
cname: pytest
canonicalize_name: coverage
cname: coverage
canonicalize_name: pytest-cov
cname: pytest-cov
canonicalize_name: pytest-mock
cname: pytest-mock
canonicalize_name: xdoctest
cname: xdoctest
canonicalize_name: sphinx
cname: sphinx
canonicalize_name: sphinx-rtd-theme
cname: sphinx-rtd-theme
canonicalize_name: sphinx-autodoc-typehints
cname: sphinx-autodoc-typehints
Using virtualenv: /Users/tdgreenw/repos/ext/hypermodern-python/.nox/tests-3-8
canonicalize_name: pip
cname: pip
canonicalize_name: None

[TypeError]
expected string or bytes-like object

Traceback (most recent call last):
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/tdgreenw/.poetry/lib/poetry/console/commands/install.py", line 47, in handle
    installer = Installer(
  File "/Users/tdgreenw/.poetry/lib/poetry/installation/installer.py", line 55, in __init__
    installed = self._get_installed()
  File "/Users/tdgreenw/.poetry/lib/poetry/installation/installer.py", line 488, in _get_installed
    return InstalledRepository.load(self._env)
  File "/Users/tdgreenw/.poetry/lib/poetry/repositories/installed_repository.py", line 26, in load
    package = Package(name, version, version)
  File "/Users/tdgreenw/.poetry/lib/poetry/packages/package.py", line 42, in __init__
    self._name = canonicalize_name(name)
  File "/Users/tdgreenw/.poetry/lib/poetry/utils/helpers.py", line 27, in canonicalize_name
    cname =  _canonicalize_regex.sub("-", name).lower()
```

So, why is `None` getting passed in here, and why would that break the entire poetry and nox integration?

**Comment by ToddG** [comment]
Nox ticket: https://github.com/theacodes/nox/issues/285

**Comment by cjolowicz** [comment]
See https://github.com/pypa/virtualenv/issues/1589
